export const SAVE_COMMENT = 'SAVE_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const FETCH_FEMALE_NAMES = 'FETCH_FEMALE_NAMES';
export const FETCH_MALE_NAMES = 'FETCH_MALE_NAMES';

export const FETCH_FEMALE_LETTER = 'FETCH_FEMALE_LETTER';
export const FETCH_MALE_LETTER = 'FETCH_MALE_LETTER';

export const SET_SELECTED_SEX = 'SET_SELECTED_SEX';
export const IS_FETCHING = 'IS_FETCHING';
export const SET_LETTER_POS = 'SET_LETTER_POS';
export const SET_NAMES = 'SET_NAMES';
export const ADD_FEMALE_LETTER = 'ADD_FEMALE_LETTER';
export const SET_HAS_MORE = 'SET_HAS_MORE';
