export const SAVE_COMMENT = 'SAVE_COMMENT';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';

export const FETCH_FEMALE_NAMES = 'FETCH_FEMALE_NAMES';
export const FETCH_MALE_NAMES = 'FETCH_MALE_NAMES';

export const FETCH_FEMALE_LETTER = 'FETCH_FEMALE_LETTER';
export const FETCH_MALE_LETTER = 'FETCH_MALE_LETTER';

export const ADD_FEMALE_LETTER = 'ADD_FEMALE_LETTER';
